development:
  host: localhost
  database: html5_website_builder_development

test:
  host: localhost
  database: html5_website_builder_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
